name: Deploy Webhook

on:
  workflow_dispatch:
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout leitosama/github-telegram-webhook
        uses: actions/checkout@v3
        with:
          repository: 'leitosama/github-telegram-webhook'

      - name: Create zip archive
        run: |
          mv templates/ github-telegram-webhook
          rm -rf github-telegram-webhook/.env.example
          rm -rf github-telegram-webhook/.templates.example
          rm -rf github-telegram-webhook/.git*
          zip -r function.zip github-telegram-webhook/*

      - name: Save key file from Secret
        run: echo ${{ secrets.YC_SA_KEY }} > key.json
  
      - uses: hashicorp/setup-terraform@v2

      - run: terraform init -no-color

      - name: Terraform plan & apply
        run: |
          terraform plan -no-color -out=tfplan
          terraform apply -no-color -auto-approve tfplan
        env:
          TF_VAR_webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          TF_VAR_chat_id: ${{ secrets.CHAT_ID }}
          TF_VAR_bot_token: ${{ secrets.BOT_TOKEN }}
          TF_VAR_zip_file: "function.zip"
          TF_VAR_user_hash: ${{ github.sha }}
          YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
          YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
          YC_SERVICE_ACCOUNT_KEY_FILE: "./key.json"

      - name: Post-action
        if: always()
        run: |
          rm -rf key.json
          rm -rf function.zip