name: Deploy Webhook

on:
  workflow_dispatch:
  push:

env:
  YC_SA_KEY_FILE: "./key.json"
  TF_VAR_zip_file: "function.zip"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        submodules: 'recursive'

      - name: Prepare zip archive
        run: |
          mv templates/ github-telegram-webhook
          rm -rf github-telegram-webhook/.env.example
          rm -rf github-telegram-webhook/.templates.example
          rm -rf github-telegram-webhook/.git*
      
      - run: zip -r ../${{ env.TF_VAR_zip_file }} ./
        working-directory: ./github-telegram-webhook

      - name: Save key file from Secret
        run: |
          python -c "import os; file = open('${{ env.YC_SA_KEY_FILE }}', 'w'); file.write(os.environ['KEY_DATA']); file.close()"
        env:
          KEY_DATA: ${{ github.ref == 'refs/heads/main' && secrets.YC_SA_KEY || secrets[format('{0}_YC_SA_KEY',github.head_ref)] }}
  
      - uses: hashicorp/setup-terraform@v2

      - uses: actions/cache@v3
        with:
          path: |
            terraform.tfstate
          key: ${{ runner.os }}-tfstate

      - run: terraform init -no-color

      - name: Terraform plan & apply (main)
        if: endsWith(github.ref, '/main')
        run: |
          terraform plan -no-color -out=tfplan
          terraform apply -no-color -auto-approve tfplan
        env:
          TF_VAR_user_hash: ${{ github.sha }}
          TF_VAR_sa_account_id: ${{ github.ref == 'refs/heads/main' && secrets.YC_SA_ACCOUNT_ID || secrets[format('{0}_YC_SA_ACCOUNT_ID',github.head_ref)] }}
          TF_VAR_secret_version_id: ${{ github.ref == 'refs/heads/main' && secrets.YC_SECRET_VERSION_ID || secrets[format('{0}_YC_SECRET_VERSION_ID',github.head_ref)] }}
          TF_VAR_secret_id: ${{ github.ref == 'refs/heads/main' && secrets.YC_SECRET_ID || secrets[format('{0}_YC_SECRET_ID',github.head_ref)] }}
          YC_CLOUD_ID: ${{ github.ref == 'refs/heads/main' && secrets.YC_CLOUD_ID || secrets[format('{0}_YC_CLOUD_ID',github.head_ref)] }}
          YC_FOLDER_ID: ${{ github.ref == 'refs/heads/main' && secrets.YC_FOLDER_ID || secrets[format('{0}_YC_FOLDER_ID',github.head_ref)] }}

      - name: Post-action
        if: always()
        run: |
          rm -rf key.json
          rm -rf function.zip