name: Test Templates && Deploy Webhook

on:
  workflow_dispatch:
  push:

env:
  YC_SERVICE_ACCOUNT_KEY_FILE: "./key.json"
  TF_VAR_zip_file: "function.zip"
  YC_CLOUD_ID: ${{ github.ref == 'refs/heads/main' && secrets.YC_CLOUD_ID || secrets[format('{0}_YC_CLOUD_ID',github.ref_name)] }}
  YC_FOLDER_ID: ${{ github.ref == 'refs/heads/main' && secrets.YC_FOLDER_ID || secrets[format('{0}_YC_FOLDER_ID',github.ref_name)] }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - run: cp github-telegram-webhook/helpers/* helpers/

      - run: pip install -r requirements.txt
          
      - name: Run template tests
        run: python ./j2test.py

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Prepare zip archive
        run: |
          mv templates/ github-telegram-webhook
          cp helpers/* github-telegram-webhook/helpers/
          rm -rf github-telegram-webhook/.env.example
          rm -rf github-telegram-webhook/.templates.example
          rm -rf github-telegram-webhook/.git*
      
      - run: zip -r ../${{ env.TF_VAR_zip_file }} ./
        working-directory: ./github-telegram-webhook

      - name: Save key file from Secret
        run: |
          python -c "import os; file = open('${{ env.YC_SERVICE_ACCOUNT_KEY_FILE }}', 'w'); file.write(os.environ['KEY_DATA']); file.close()"
        env:
          KEY_DATA: ${{ github.ref == 'refs/heads/main' && secrets.YC_SA_KEY || secrets[format('{0}_YC_SA_KEY',github.ref_name)] }}
  
      - uses: hashicorp/setup-terraform@v2

      - run: |
          terraform init -no-color \
          -backend-config="endpoint=${{ vars.TF_BACKEND_S3_ENDPOINT }}" \
          -backend-config="bucket=${{ vars.TF_BACKEND_S3_BUCKET }}" \ 
          -backend-config="region=ru-central1" \
          -backend-config="key=${{ env.YC_FOLDER_ID }}/terraform.tfstate" \
          -backend-config="access_key=${{ github.ref == 'refs/heads/main' && secrets.TF_BACKEND_S3_SA_ID || secrets[format('{0}_TF_BACKEND_S3_SA_ID',github.ref_name)] }}" \
          -backend-config="secret_key=${{ github.ref == 'refs/heads/main' && secrets.TF_BACKEND_S3_SA_SECRET || secrets[format('{0}_TF_BACKEND_S3_SA_SECRET',github.ref_name)] }}" \
          -backend-config="skip_region_validation=true" \ 
          -backend-config="skip_credentials_validation=true"

      - name: Terraform plan & apply
        run: |
          terraform plan -no-color -out=tfplan
          terraform apply -no-color -auto-approve tfplan
        env:
          TF_VAR_user_hash: ${{ github.sha }}
          TF_VAR_sa_account_id: ${{ github.ref == 'refs/heads/main' && secrets.YC_SA_ACCOUNT_ID || secrets[format('{0}_YC_SA_ACCOUNT_ID',github.ref_name)] }}
          TF_VAR_bot_token: ${{ github.ref == 'refs/heads/main' && secrets.BOT_TOKEN || secrets[format('{0}_BOT_TOKEN',github.ref_name)] }}
          TF_VAR_webhook_secret: ${{ github.ref == 'refs/heads/main' && secrets.WEBHOOK_SECRET || secrets[format('{0}_WEBHOOK_SECRET',github.ref_name)] }}
          TF_VAR_chat_id: ${{ github.ref == 'refs/heads/main' && secrets.CHAT_ID || secrets[format('{0}_CHAT_ID',github.ref_name)] }}
          TF_VAR_thread_id: ${{ github.ref == 'refs/heads/main' && secrets.THREAD_ID || secrets[format('{0}_THREAD_ID',github.ref_name)] }}
          TF_VAR_project_name: ${{ github.ref_name }}


      - name: Post-action
        if: always()
        run: |
          rm -rf key.json
          rm -rf function.zip